In [1]:
import numpy as np

In [4]:
a = [[0, 1],[1,1]]
b=  [[4, 1],[2, 1]]
# Dot product of a and b
print(np.dot(a,b))

[[2 1]
 [6 2]]


In [44]:
a = (4, -3, -2, 1, 3, 4)
a=np.array(a)#converting array to numpy array

In [45]:
print("Sum=",np.sum(a))#Sum of array elements
print("Max=",np.max(a))#Maximum of array elements
print("Min=",np.min(a))#Minimum of array elements
print("Mean=",np.mean(a))#Mean of array elements
print("Standard Deviation=",np.std(a))#Standard deviation of array elements

Sum= 7
Max= 4
Min= -3
Mean= 1.1666666666666667
Standard Deviation= 2.793842435706702


In [53]:
#np.argmin(a)
np.where(a==np.min(a))

(array([1]),)

In [52]:
#np.argmax(a)
np.where(a==np.max(a))

(array([0, 5]),)

In [17]:
a=np.arange(36)
a #creating array of elements 0 to 35

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [19]:
a=np.arange(36).reshape(6,6)# Giving the shape of 6X6 matrix
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
a[2,[2,3,4]] #Getting 3rd row 3rd to 5th column elements

array([14, 15, 16])

In [26]:
a[0:2,0:5] #find all elements of 1st and 2nd row except last column

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[::-1] #Reversing the rows

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [54]:
#Find the time taken to execute the code that generates 25000 random numbers between 0 and 5000 and repeat this 100 times
import random
import time
start=time.time()
print(start)
for i in range(101):
  for i in range(25001):
    random.randint(0,5001)
stop=time.time()
print(stop)
print(stop-start)


1696846843.4183707
1696846847.4051266
3.986755847930908


In [35]:
"""Write a Python code for the following:
Consider the hypothesis space H defined by conjunctions of literals based on n boolean variables.
The size IHI of this hypothesis space is 3^n. If a learner attempts to learn a target concept described
by conjunctions of up to 10 boolean literals, and we desire a 95% probability that it will learn a
hypothesis with error less than 0.1, then it suffices to present m randomly drawn training
examples. Find the value of m sufficient for this case. Given [δ = 5% (0.05); ϵ = 0.1]"""

import math
h=3^10
e=0.1
d=0.05
m=(1/e)*(math.log(h)+math.log(1/d))
print(m)

51.92956850890211
